name: Bash CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run ShellCheck Linting
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: 'README.md'
